@tool
extends EditorPlugin

func _enter_tree():
	add_custom_type("ItemDescriptor", "Resource", preload ("item_descriptor.gd"), preload ("icons/item_descriptor.png"))
	add_custom_type("ItemFilter", "Resource", preload ("filters/item_filter.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemFilterAnd", "Resource", preload ("filters/item_filter_and.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemFilterByCategory", "Resource", preload ("filters/item_filter_by_category.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemFilterByDescriptor", "Resource", preload ("filters/item_filter_by_descriptor.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemFilterByDisplayName", "Resource", preload ("filters/item_filter_by_display_name.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemFilterByItemName", "Resource", preload ("filters/item_filter_by_item_name.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemFilterNegate", "Resource", preload ("filters/item_filter_negate.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemFilterNoDuplicates", "Resource", preload ("filters/item_filter_no_duplicates.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemFilterOr", "Resource", preload ("filters/item_filter_or.gd"), preload ("icons/item_filter.png"))
	add_custom_type("ItemInstance", "Node", preload ("item_instance.gd"), preload ("icons/item.png"))
	add_custom_type("ItemInteractor", "Node", preload ("item_interactor.gd"), preload ("icons/item.png"))
	add_custom_type("ItemInventory", "Node", preload ("item_inventory.gd"), preload ("icons/item_inventory.png"))
	add_custom_type("ItemScriptBase", "Node", preload ("item_script_base.gd"), preload ("icons/item_view_model.png"))
	add_custom_type("ItemViewModel2D", "Node", preload ("item_view_model_2d.gd"), preload ("icons/item_view_model.png"))
	add_custom_type("ItemViewModel3D", "Node", preload ("item_view_model_3d.gd"), preload ("icons/item_view_model.png"))
	add_custom_type("WorldItem2D", "RigidBody2D", preload ("world_item_2d.gd"), preload ("icons/world_item_2d.png"))
	add_custom_type("WorldItem3D", "RigidBody3D", preload ("world_item_3d.gd"), preload ("icons/world_item_3d.png"))

func _exit_tree():
	remove_custom_type("WorldItem3D")
	remove_custom_type("WorldItem2D")
	remove_custom_type("ItemViewModel3D")
	remove_custom_type("ItemViewModel2D")
	remove_custom_type("ItemScriptBase")
	remove_custom_type("ItemInventory")
	remove_custom_type("ItemInteractor")
	remove_custom_type("ItemInstance")
	remove_custom_type("ItemFilterOr")
	remove_custom_type("ItemFilterNoDuplicates")
	remove_custom_type("ItemFilterNegate")
	remove_custom_type("ItemFilterByItemName")
	remove_custom_type("ItemFilterByDisplayName")
	remove_custom_type("ItemFilterByDescriptor")
	remove_custom_type("ItemFilterByCategory")
	remove_custom_type("ItemFilterAnd")
	remove_custom_type("ItemFilter")
	remove_custom_type("ItemDescriptor")
